export enum ErrorCode {
  // Auth Domain
  AUTH_TOKEN_MISSING = 'AUTH_TOKEN_MISSING',
  AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED',
  AUTH_UNAUTHORIZED = 'AUTH_UNAUTHORIZED',
  AUTH_FORBIDDEN = 'AUTH_FORBIDDEN',

  // Geo Domain
  GEO_POLYGON_INVALID = 'GEO_POLYGON_INVALID',
  GEO_LOCATION_OUT_OF_BOUNDS = 'GEO_LOCATION_OUT_OF_BOUNDS',
  GEO_INVALID_COORDINATES = 'GEO_INVALID_COORDINATES',

  // Anti-Cheat Domain
  CHEAT_SPEED_TOO_HIGH = 'CHEAT_SPEED_TOO_HIGH',
  CHEAT_MOCK_LOCATION_DETECTED = 'CHEAT_MOCK_LOCATION_DETECTED',
  CHEAT_INVALID_HARDWARE_DATA = 'CHEAT_INVALID_HARDWARE_DATA',
  CHEAT_MULTIPLE_DEVICES = 'CHEAT_MULTIPLE_DEVICES',

  // Business Domain
  BIZ_CLUB_FULL = 'BIZ_CLUB_FULL',
  BIZ_TERRITORY_PROTECTED = 'BIZ_TERRITORY_PROTECTED',
  BIZ_INSUFFICIENT_COINS = 'BIZ_INSUFFICIENT_COINS',
  BIZ_RESOURCE_NOT_FOUND = 'BIZ_RESOURCE_NOT_FOUND',
  BIZ_VALIDATION_FAILED = 'BIZ_VALIDATION_FAILED',
  BIZ_TOO_MANY_REQUESTS = 'BIZ_TOO_MANY_REQUESTS',

  // System
  SYS_INTERNAL_ERROR = 'SYS_INTERNAL_ERROR',
  SYS_DATABASE_ERROR = 'SYS_DATABASE_ERROR',
}

export class AppError extends Error {
  constructor(
    public code: ErrorCode,
    public message: string,
    public statusCode: number = 400,
    public details?: any
  ) {
    super(message);
    this.name = 'AppError';
  }
}
