export enum ErrorCode {
  // Auth Domain
  AUTH_TOKEN_MISSING = 'AUTH_TOKEN_MISSING',
  AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED',
  AUTH_UNAUTHORIZED = 'AUTH_UNAUTHORIZED',
  AUTH_FORBIDDEN = 'AUTH_FORBIDDEN',

  // Geo Domain
  GEO_POLYGON_INVALID = 'GEO_POLYGON_INVALID',
  GEO_LOCATION_OUT_OF_BOUNDS = 'GEO_LOCATION_OUT_OF_BOUNDS',
  GEO_INVALID_COORDINATES = 'GEO_INVALID_COORDINATES',

  // Anti-Cheat Domain
  CHEAT_SPEED_TOO_HIGH = 'CHEAT_SPEED_TOO_HIGH',
  CHEAT_MOCK_LOCATION_DETECTED = 'CHEAT_MOCK_LOCATION_DETECTED',
  CHEAT_INVALID_HARDWARE_DATA = 'CHEAT_INVALID_HARDWARE_DATA',
  CHEAT_MULTIPLE_DEVICES = 'CHEAT_MULTIPLE_DEVICES',
  CHEAT_GENERAL_VIOLATION = 'CHEAT_GENERAL_VIOLATION',

  // Request/Response Domain
  REQ_BAD_PARAM = 'REQ_BAD_PARAM',
  RES_NOT_FOUND = 'RES_NOT_FOUND',

  // Business Domain
  BIZ_CLUB_FULL = 'BIZ_CLUB_FULL',
  BIZ_TERRITORY_PROTECTED = 'BIZ_TERRITORY_PROTECTED',
  BIZ_INSUFFICIENT_COINS = 'BIZ_INSUFFICIENT_COINS',
  BIZ_RESOURCE_NOT_FOUND = 'BIZ_RESOURCE_NOT_FOUND',
  BIZ_VALIDATION_FAILED = 'BIZ_VALIDATION_FAILED',
  BIZ_TOO_MANY_REQUESTS = 'BIZ_TOO_MANY_REQUESTS',
  BIZ_LOGIC_ERROR = 'BIZ_LOGIC_ERROR',

  // System
  SYS_INTERNAL_ERROR = 'SYS_INTERNAL_ERROR',
  SYS_DATABASE_ERROR = 'SYS_DATABASE_ERROR',
}

export const ERROR_HTTP_STATUS: Record<ErrorCode, number> = {
  // Auth Domain
  [ErrorCode.AUTH_TOKEN_MISSING]: 401,
  [ErrorCode.AUTH_TOKEN_EXPIRED]: 401,
  [ErrorCode.AUTH_UNAUTHORIZED]: 401,
  [ErrorCode.AUTH_FORBIDDEN]: 403,

  // Geo Domain
  [ErrorCode.GEO_POLYGON_INVALID]: 400,
  [ErrorCode.GEO_LOCATION_OUT_OF_BOUNDS]: 400,
  [ErrorCode.GEO_INVALID_COORDINATES]: 400,

  // Anti-Cheat Domain
  [ErrorCode.CHEAT_SPEED_TOO_HIGH]: 403,
  [ErrorCode.CHEAT_MOCK_LOCATION_DETECTED]: 403,
  [ErrorCode.CHEAT_INVALID_HARDWARE_DATA]: 400,
  [ErrorCode.CHEAT_MULTIPLE_DEVICES]: 403,
  [ErrorCode.CHEAT_GENERAL_VIOLATION]: 403,

  // Request/Response Domain
  [ErrorCode.REQ_BAD_PARAM]: 400,
  [ErrorCode.RES_NOT_FOUND]: 404,

  // Business Domain
  [ErrorCode.BIZ_CLUB_FULL]: 409,
  [ErrorCode.BIZ_TERRITORY_PROTECTED]: 403,
  [ErrorCode.BIZ_INSUFFICIENT_COINS]: 409,
  [ErrorCode.BIZ_RESOURCE_NOT_FOUND]: 404,
  [ErrorCode.BIZ_VALIDATION_FAILED]: 400,
  [ErrorCode.BIZ_TOO_MANY_REQUESTS]: 429,
  [ErrorCode.BIZ_LOGIC_ERROR]: 400,

  // System
  [ErrorCode.SYS_INTERNAL_ERROR]: 500,
  [ErrorCode.SYS_DATABASE_ERROR]: 500,
};

export class AppError extends Error {
  public statusCode: number;

  constructor(
    public code: ErrorCode,
    public message: string,
    statusCode?: number,
    public details?: any
  ) {
    super(message);
    this.name = 'AppError';
    this.statusCode = statusCode ?? ERROR_HTTP_STATUS[code] ?? 400;
  }
}
