BEGIN;
ALTER TABLE "profiles" RENAME COLUMN "isProfilePublic" TO "is_profile_public";
ALTER TABLE "profiles" RENAME COLUMN "backgroundUrl" TO "background_url";
ALTER TABLE "profiles" RENAME COLUMN "blockedMe" TO "blocked_me";
ALTER TABLE "profiles" RENAME COLUMN "blockedByMe" TO "blocked_by_me";
ALTER TABLE "profiles" RENAME COLUMN "profileLikesGiven" TO "profile_likes_given";
ALTER TABLE "profiles" RENAME COLUMN "profileLikesReceived" TO "profile_likes_received";
ALTER TABLE "profiles" RENAME COLUMN "userBackgrounds" TO "user_backgrounds";
ALTER TABLE "profiles" RENAME COLUMN "watchActivities" TO "watch_activities";
ALTER TABLE "UserWallet" RENAME TO "user_wallets";
ALTER TABLE "WalletTransaction" RENAME TO "wallet_transactions";
ALTER TABLE "DailyStat" RENAME TO "daily_stats";
ALTER TABLE "daily_stats" RENAME COLUMN "redCount" TO "red_count";
ALTER TABLE "daily_stats" RENAME COLUMN "blueCount" TO "blue_count";
ALTER TABLE "daily_stats" RENAME COLUMN "totalTerritories" TO "total_territories";
ALTER TABLE "daily_stats" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "ProvinceStat" RENAME TO "province_stats";
ALTER TABLE "province_stats" RENAME COLUMN "provinceName" TO "province_name";
ALTER TABLE "province_stats" RENAME COLUMN "totalTerritoryArea" TO "total_territory_area";
ALTER TABLE "FactionStatsCache" RENAME TO "faction_stats_caches";
ALTER TABLE "runs" RENAME COLUMN "eventsLog" TO "events_log";
ALTER TABLE "runs" RENAME COLUMN "antiCheatLog" TO "anti_cheat_log";
ALTER TABLE "runs" RENAME COLUMN "isValid" TO "is_valid";
ALTER TABLE "runs" RENAME COLUMN "totalSteps" TO "total_steps";
ALTER TABLE "runs" RENAME COLUMN "aiSummary" TO "ai_summary";
ALTER TABLE "profile_likes" RENAME COLUMN "userId" TO "user_id";
ALTER TABLE "profile_likes" RENAME COLUMN "likerId" TO "liker_id";
ALTER TABLE "profile_likes" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "blocked_users" RENAME COLUMN "blockerId" TO "blocker_id";
ALTER TABLE "blocked_users" RENAME COLUMN "blockedId" TO "blocked_id";
ALTER TABLE "blocked_users" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "backgrounds" RENAME COLUMN "previewUrl" TO "preview_url";
ALTER TABLE "backgrounds" RENAME COLUMN "imageUrl" TO "image_url";
ALTER TABLE "backgrounds" RENAME COLUMN "isDefault" TO "is_default";
ALTER TABLE "backgrounds" RENAME COLUMN "conditionType" TO "condition_type";
ALTER TABLE "backgrounds" RENAME COLUMN "conditionValue" TO "condition_value";
ALTER TABLE "backgrounds" RENAME COLUMN "priceCoins" TO "price_coins";
ALTER TABLE "backgrounds" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "backgrounds" RENAME COLUMN "userBackgrounds" TO "user_backgrounds";
ALTER TABLE "user_backgrounds" RENAME COLUMN "userId" TO "user_id";
ALTER TABLE "user_backgrounds" RENAME COLUMN "backgroundId" TO "background_id";
ALTER TABLE "user_backgrounds" RENAME COLUMN "acquiredAt" TO "acquired_at";
ALTER TABLE "rewardLog" RENAME TO "reward_logs";
ALTER TABLE "reward_logs" RENAME COLUMN "userId" TO "user_id";
ALTER TABLE "reward_logs" RENAME COLUMN "referenceId" TO "reference_id";
ALTER TABLE "reward_logs" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "expLog" RENAME TO "exp_logs";
ALTER TABLE "exp_logs" RENAME COLUMN "userId" TO "user_id";
ALTER TABLE "exp_logs" RENAME COLUMN "oldExp" TO "old_exp";
ALTER TABLE "exp_logs" RENAME COLUMN "newExp" TO "new_exp";
ALTER TABLE "exp_logs" RENAME COLUMN "createdAt" TO "created_at";
COMMIT;