import { Location } from '@/hooks/useRunningTracker';

/**
 * Standard Server Action Response wrapper.
 */
export interface ActionResponse<T = any> {
    success: boolean;
    message?: string;
    data?: T;
    error?: string;
}

/**
 * Data Transfer Object for strictly typed run submissions.
 * Front-end strictly sends this payload; back-end strictly validates it.
 */
export interface RunRecordDTO {
    /** 
     * UUID v4 generated by the client to prevent duplicate submissions 
     * under poor network conditions (idempotency key).
     */
    idempotencyKey: string;

    /** Distance in meters */
    distance: number;

    /** Duration in seconds */
    duration: number;

    /** 
     * The raw trajectory path of GPS points. 
     * For large paths, it's serialized to JSON on the server.
     */
    path: Location[];

    /**
     * Closed territory polygons claimed during this run session.
     */
    polygons: Location[][];

    /** UNIX timestamp when the run was completed/saved */
    timestamp: number;

    /** Estimated calories burned */
    calories?: number;

    /** Estimated steps taken */
    steps?: number;

    /**
     * Optional manual interactions map (number of paused/resumed, etc)
     */
    manualLocationCount?: number;
}
