export interface AchievementDefinition {
  id: string
  title: string
  description: string
  icon: React.ElementType
  image?: string // Path to badge image in public folder
  category: AchievementCategory
  rarity: AchievementRarity
  maxProgress: number
  rewards: {
    xp?: number
    coins?: number
    title?: string
    badge?: string
  }
}

export const ACHIEVEMENT_DEFINITIONS: AchievementDefinition[] = [
  // --- 探索 (Exploration) ---
  {
    id: "exploration_1",
    title: "初出茅庐",
    description: "完成你的第一次探索",
    icon: Footprints,
    image: "/badges/badge_exploration_novice.png",
    category: "territory",
    rarity: "common",
    maxProgress: 1,
    rewards: { xp: 50, coins: 20 },
  },
  {
    id: "exploration_2",
    title: "第一块领地",
    description: "占领你的第一块领地",
    icon: Flag,
    image: "/badges/badge_first_territory.png",
    category: "territory",
    rarity: "common",
    maxProgress: 1,
    rewards: { xp: 100, coins: 50 },
  },
  {
    id: "exploration_3",
    title: "拓荒者 (铜)",
    description: "占领10块领地",
    icon: Award,
    image: "/badges/badge_pioneer_bronze.png",
    category: "territory",
    rarity: "common",
    maxProgress: 10,
    rewards: { xp: 200, coins: 100 },
  },
  {
    id: "exploration_4",
    title: "城市探险家",
    description: "在3个不同的区域拥有领地",
    icon: MapPin,
    image: "/badges/badge_city_explorer.png",
    category: "territory",
    rarity: "rare",
    maxProgress: 3,
    rewards: { xp: 300, coins: 150 },
  },
  {
    id: "exploration_5",
    title: "街区巡视员",
    description: "连续3天访问同一街区",
    icon: Eye,
    image: "/badges/badge_street_patrol.png",
    category: "territory",
    rarity: "common",
    maxProgress: 3,
    rewards: { xp: 150, coins: 50 },
  },
  {
    id: "exploration_6",
    title: "区域绘图师",
    description: "点亮一个完整区域的所有迷雾",
    icon: MapIcon,
    image: "/badges/badge_cartographer.png",
    category: "territory",
    rarity: "epic",
    maxProgress: 1,
    rewards: { xp: 500, coins: 300 },
  },
  {
    id: "exploration_7",
    title: "城市地主",
    description: "拥有超过100块领地",
    icon: Building,
    image: "/badges/badge_landlord.png",
    category: "territory",
    rarity: "epic",
    maxProgress: 100,
    rewards: { xp: 800, coins: 500, title: "地主" },
  },
  {
    id: "exploration_8",
    title: "一方霸主",
    description: "在某个区域占有率达到50%",
    icon: Crown,
    image: "/badges/badge_regional_overlord.png",
    category: "territory",
    rarity: "legendary",
    maxProgress: 1,
    rewards: { xp: 1000, coins: 800, title: "霸主" },
  },
  {
    id: "exploration_9",
    title: "世界尽头",
    description: "到达地图的最边缘",
    icon: Compass,
    image: "/badges/badge_world_end.png",
    category: "territory",
    rarity: "legendary",
    maxProgress: 1,
    rewards: { xp: 1500, coins: 1000 },
  },

  // --- 耐力 (Endurance) ---
  {
    id: "endurance_1",
    title: "起跑线",
    description: "累计跑步1公里",
    icon: Footprints,
    image: "/badges/badge_starting_line.png",
    category: "running",
    rarity: "common",
    maxProgress: 1,
    rewards: { xp: 50, coins: 20 },
  },
  {
    id: "endurance_2",
    title: "长跑健将",
    description: "单次跑步超过10公里",
    icon: Zap,
    image: "/badges/badge_long_runner.png",
    category: "running",
    rarity: "rare",
    maxProgress: 10,
    rewards: { xp: 300, coins: 150 },
  },
  {
    id: "endurance_3",
    title: "全马大神",
    description: "累计跑步距离达到42.195公里",
    icon: Medal,
    image: "/badges/badge_marathon_god.png",
    category: "running",
    rarity: "epic",
    maxProgress: 42,
    rewards: { xp: 1000, coins: 500, title: "马拉松大神" },
  },
  {
    id: "endurance_4",
    title: "追风者 (铜)",
    description: "累计跑步50公里",
    icon: Wind,
    image: "/badges/badge_wind_chaser_bronze.png",
    category: "running",
    rarity: "common",
    maxProgress: 50,
    rewards: { xp: 200, coins: 100 },
  },
  {
    id: "endurance_5",
    title: "城市行者",
    description: "累计跑步100公里",
    icon: Navigation,
    image: "/badges/badge_city_walker.png",
    category: "running",
    rarity: "rare",
    maxProgress: 100,
    rewards: { xp: 500, coins: 250 },
  },
  {
    id: "endurance_6",
    title: "百公里勋章",
    description: "单月累计跑步100公里",
    icon: Medal,
    image: "/badges/badge_100km.png",
    category: "running",
    rarity: "epic",
    maxProgress: 100,
    rewards: { xp: 800, coins: 400 },
  },
  {
    id: "endurance_7",
    title: "超凡耐力",
    description: "连续跑步30天",
    icon: Flame,
    image: "/badges/badge_super_stamina.png",
    category: "running",
    rarity: "legendary",
    maxProgress: 30,
    rewards: { xp: 1500, coins: 800, badge: "耐力王" },
  },
  {
    id: "endurance_8",
    title: "跑鞋终结者",
    description: "累计跑步500公里",
    icon: Trophy,
    image: "/badges/badge_shoe_killer.png",
    category: "running",
    rarity: "legendary",
    maxProgress: 500,
    rewards: { xp: 2000, coins: 1000 },
  },
  {
    id: "endurance_9",
    title: "千里马",
    description: "累计跑步1000公里",
    icon: Crown,
    image: "/badges/badge_thousand_miles.png",
    category: "running",
    rarity: "legendary",
    maxProgress: 1000,
    rewards: { xp: 5000, coins: 2000, title: "千里马" },
  },
  {
    id: "endurance_10",
    title: "追风者 (金)",
    description: "平均配速低于4:00/km",
    icon: Zap,
    image: "/badges/badge_wind_chaser_gold.png",
    category: "running",
    rarity: "epic",
    maxProgress: 1,
    rewards: { xp: 1000, coins: 500 },
  },

  // --- 征服 (Conquest) ---
  {
    id: "conquest_1",
    title: "不速之客",
    description: "从其他玩家手中夺取1块领地",
    icon: Swords,
    image: "/badges/badge_intruder.png",
    category: "territory",
    rarity: "common",
    maxProgress: 1,
    rewards: { xp: 100, coins: 50 },
  },
  {
    id: "conquest_2",
    title: "领地掠夺者",
    description: "夺取10块领地",
    icon: Axe,
    image: "/badges/badge_territory_raider.png",
    category: "territory",
    rarity: "rare",
    maxProgress: 10,
    rewards: { xp: 300, coins: 150 },
  },
  {
    id: "conquest_3",
    title: "征服王",
    description: "夺取100块领地",
    icon: Skull,
    image: "/badges/badge_conqueror_king.png",
    category: "territory",
    rarity: "legendary",
    maxProgress: 100,
    rewards: { xp: 2000, coins: 1000, title: "征服王" },
  },

  // --- 隐藏 (Hidden) ---
  {
    id: "hidden_1",
    title: "早起鸟",
    description: "在清晨5点-7点之间完成跑步",
    icon: Sunrise,
    image: "/badges/badge_early_bird.png",
    category: "special",
    rarity: "rare",
    maxProgress: 1,
    rewards: { xp: 200, coins: 100 },
  },
  {
    id: "hidden_2",
    title: "夜行侠",
    description: "在深夜22点-4点之间完成跑步",
    icon: Moon,
    image: "/badges/badge_night_walker.png",
    category: "special",
    rarity: "rare",
    maxProgress: 1,
    rewards: { xp: 200, coins: 100 },
  },
  {
    id: "hidden_3",
    title: "闪电侠",
    description: "在雨天完成一次跑步",
    icon: CloudLightning,
    image: "/badges/badge_flash.png",
    category: "special",
    rarity: "epic",
    maxProgress: 1,
    rewards: { xp: 500, coins: 200 },
  },
]

import {
  Footprints,
  Medal,
  Hexagon,
  Crown,
  Swords,
  Users,
  Flame,
  MapPin,
  Target,
  Star,
  Flag,
  Award,
  Eye,
  Map as MapIcon,
  Building,
  Compass,
  Zap,
  Wind,
  Navigation,
  Trophy,
  Axe,
  Skull,
  Sunrise,
  Moon,
  CloudLightning,
} from "lucide-react"

export type AchievementCategory = "all" | "running" | "territory" | "social" | "special"
export type AchievementRarity = "common" | "rare" | "epic" | "legendary"
